(function(){ "use strict"; var g=true,i=null,k=false,ba=this;function ca(a,b,c){a=a.split(".");c=c||ba;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:c[d]={}}var m=Date.now||function(){return+new Date};var da,ea,fa=[],ga={},ha=i;function ia(){var a=m();fa.forEach(function(b,c){if(da)if(!b.Fb){if(ha)if(!b.name||ha.indexOf(b.name)===-1)return;if(!(a-b.eb<=b.Zb)){b.eb=a;b.tb-=1;if(b.tb<=0)if(!b.Ab||b.tb<0){fa.remove(c);delete ga[b.name];if(b.Ab)return}b.Yb.apply(b.dc,b.Rb)}}});fa.length||ja()}function ka(a,b,c,d,e,f,h){var o=m(),l=f?ga[f]:i;if(!l){l={Yb:a,name:f,dc:h,eb:e?-Infinity:o};fa.push(l);if(f)ga[f]=l}l.Rb=d||[];l.tb=c;l.Zb=Math.max(b,25);l.Ab=e;l.Fb=k;da||(da=window.setInterval(ia,25))}
function la(a,b,c,d,e){ka(a,b,1,c,k,d,e)}function ma(a,b,c,d,e,f){ka(a,b,c,d,k,e,f)}function na(a,b,c,d){ka(a,0,1,b,k,c,d)}function oa(a,b){ha=a;if(b)ea=setTimeout(pa,b)}function pa(){ha=i;if(ea){window.clearTimeout(ea);ea=i}}function qa(a){delete ga[a];fa.forEach(function(b,c){if(b.name===a){fa.remove(c);b.Fb=g}})}function ja(){da&&window.clearInterval(da);pa();da=i;fa=[];ga={}};m();if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,b){var c,d;c=b||0;for(d=this.length;c<d;c+=1)if(this[c]===a)return c;return-1};if(!Array.Bb)Array.Bb=function(a){return Object.prototype.toString.apply(a)==="[object Array]"};Array.prototype.remove=function(a,b){var c=this.slice((b||a)+1||this.length);this.length=a<0?this.length+a:a;return this.push.apply(this,c)};
if(!Array.prototype.forEach)Array.prototype.forEach=function(a,b){for(var c=0,d=this.length;c<d;c+=1)c in this&&a.call(b,this[c],c,this)};if(!Array.prototype.some)Array.prototype.some=function(a,b){for(var c=0,d=this.length;c<d;c+=1)if(c in this&&a.call(b,this[c],c,this))return g;return k};if(!Array.prototype.every)Array.prototype.every=function(a,b){for(var c=0,d=this.length;c<d;c+=1)if(c in this&&!a.call(b,this[c],c,this))return k;return g};
if(!Array.prototype.map)Array.prototype.map=function(a,b){for(var c=0,d=this.length,e=[];c<d;c+=1)if(c in this)e[c]=a.call(b,this[c],c,this);return e};if(!Array.prototype.filter)Array.prototype.filter=function(a,b){for(var c=0,d,e=this.length,f=[];c<e;c+=1)if(c in this){d=this[c];a.call(b,d,c,this)&&f.push(d)}return f};function u(a){return Array.prototype.slice.call(a,0)}if("attachEvent"in document)u=function(a){var b,c,d=[];b=0;for(c=a.length;b<c;b+=1)d.push(a[b]);return d};var ra,sa,v=window.navigator.userAgent.toLowerCase(),w=!("localStorage"in window&&"querySelectorAll"in document&&"JSON"in window),ta=document.compatMode!=="BackCompat"&&"XMLHttpRequest"in window&&!!(document.addEventListener||document.attachEvent)&&!!(document.documentElement.currentStyle||window.getComputedStyle)&&("querySelectorAll"in document||"attachEvent"in document&&!("addEventListener"in document)),ua="documentMode"in document&&document.documentMode<=7,wa=va==="android"||/mobile/.test(v),xa=
window.screen.width<=600,ya=/webkit/.test(v)?/chrome|safari/.test(v)?/(chrome|safari)/.exec(v)[0]:"webkit":/opera/.test(v)?"opera":/msie/.test(v)?"msie":!/compatible/.test(v)&&/mozilla/.test(v)?"mozilla":"unknown",va=(/(android|ipad|iphone|ipod|win|mac|linux)/.exec(window.navigator.platform?window.navigator.platform.toLowerCase():/android/.test(v)?"android":"unknown")||["unknown"])[0],za=function(){switch(ya){case "chrome":case "safari":case "webkit":return"-webkit-";case "mozilla":return"-moz-";
case "msie":return"-ms-";case "opera":return"-o-";default:return""}}(),Aa=function(){switch(ya){case "chrome":case "safari":case "webkit":return"Webkit";case "mozilla":return"Moz";case "msie":return"ms";case "opera":return"O";default:return""}}();function Ba(a,b,c){var d=document.documentElement.style;b=b&&Aa?Aa+a.charAt(0).toUpperCase()+a.substr(1):k;return!c&&typeof d[a]!=="undefined"||!!b&&typeof d[b]!=="undefined"}
var Ca="orientation"in window,Da="createTouch"in document||/android/.test(v),Ea=function(){if(window.navigator.plugins&&window.navigator.plugins.length)return!!window.navigator.plugins["Shockwave Flash"];else if("ActiveXObject"in window)try{return!!new window.qc("ShockwaveFlash.ShockwaveFlash.7")}catch(a){return k}return k}(),Fa=function(){if(w)return k;if("CSSFontFaceRule"in window)return g;if(ya==="msie")return g;return k}(),Ga="getItems"in document,Ha="getContext"in document.createElement("canvas"),
Ia="canPlayType"in document.createElement("video"),Ja="localStorage"in window&&!w,Ka="applicationCache"in window,La=Ba("transformProperty")||Ba("transform",g,g),Ma,Na=Ba("perspectiveProperty")||Ba("perspective",g,g);
if(Na&&"WebkitPerspective"in document.documentElement.style&&ya!=="safari"){var Pa=document.createElement("style"),Qa=document.createElement("div"),Ra="@media (perspective)",Sa;Ra+=",("+za+"perspective)";Pa.textContent=Ra+"{#ts-test {height:3px}}";Qa.setAttribute("id","ts-test");document.documentElement.appendChild(Pa);document.documentElement.appendChild(Qa);Sa=Qa.offsetHeight===3;document.documentElement.removeChild(Pa);document.documentElement.removeChild(Qa);Na=Sa}Ma=Na;
var Ta=Ba("transitionProperty",g);function A(a){return a?"":"no-"}var Ua=k;
function Va(){if(!ra){ra=[];ra.push("js",A(Ha)+"canvas",A(Ja)+"localstorage",A(Ia)+"video",A(Ka)+"applicationcache",A(Fa)+"fontface",A(Da)+"touch",A(La)+"csstransforms",A(Ma)+"csstransforms3d",A(Ta)+"csstransitions",A(Ga)+"microdata",A(ta)+"treesaver",A(Ea)+"flash",A(Ca)+"orientation",A(w)+"legacy",A(wa)+"mobile",A(xa)+"smallscreen",A(B.gb())+"cached",A(k)+"nativeapp","browser-"+ya,"os-"+va)}sa=[A(!B.xa())+"offline"];if(Ca)sa.push("orientation-"+(window.orientation?"horizontal":"vertical"));var a=
document.documentElement.className;if(!Ua){Ua=g;a=a?a.replace(/no-js|no-treesaver/g,""):"";a+=" "+ra.join(" ")}a=a.replace(Wa,"");a+=" "+sa.join(" ");document.documentElement.className=a.split(/\s+/).join(" ")}var Xa=["offline","orientation-vertical","orientation-horizontal"],Wa=function(){var a=Xa.map(function(b){return"((no-)?"+b+")"});return RegExp(a.join("|"))}();
function Ya(a,b){if(!a.length)return g;return a.every(function(c){var d=c.substr(0,3)==="no-";c=d?c.substr(3):c;var e=ra.concat(b?sa:[]);if(d)return e.indexOf(c)===-1;else{if(e.indexOf(c)!==-1)return g;if(!b&&Xa.indexOf(c)!==-1)return g;return k}})};function C(a,b){if(a.className)D(a,b)||(a.className+=" "+b);else a.className=b;if(w)a.className=a.className}function Za(a,b){a.className=a.className.replace(RegExp("(^|\\s)"+b+"(\\s|$)"),"$2")}function D(a,b){return!!(a.className&&RegExp("(^|\\s)"+b+"(\\s|$)").test(a.className))}
function E(a,b){b||(b=document);var c=[];if("querySelectorAll"in b)c=u(b.querySelectorAll("."+a));else{var d=RegExp("(^|\\s)"+a+"(\\s|$)");u(b.getElementsByTagName("*")).forEach(function(e){d.test(e.className)&&c.push(e)})}return c}function $a(a,b){b||(b=document);return u(b.getElementsByTagName(a))}
function ab(a,b,c,d){d||(d=document);c=c||"*";if("querySelectorAll"in d){d||(d=document);return u(d.querySelectorAll(c+"["+a+(b?'~="'+b+'"':"")+"]"))}else{var e=[];c=$a(c,d);var f=b?RegExp("(^|\\s)"+b.replace(/[.*+?\^${}()|\[\]\/\\]/g,"\\$&")+"(\\s|$)"):{test:function(){return g}};a=a==="class"?"className":a;c.forEach(function(h){G(h,a)&&f.test(h.getAttribute(a))&&e.push(h)});return e}}
function G(a,b){return"hasAttribute"in a?a.hasAttribute(b):b==="className"?a.className!=="":a.getAttribute(b)!==i}function bb(a){for(;a.firstChild;)a.removeChild(a.firstChild)}function cb(a){if("outerHTML"in a)return a.outerHTML;a=a.cloneNode(g);var b;db.appendChild(a);b=db.innerHTML;db.removeChild(a);return b}function eb(a){document.body.appendChild(db);db.innerHTML=a;a=db.firstChild;bb(db);document.body.removeChild(db);if(!a||a.nodeType!==1)return i;return a}
if("Node"in window&&Node.prototype&&!Node.prototype.contains)Node.prototype.contains=function(a){return!!(this.compareDocumentPosition(a)&16)};var db=document.createElement("div");db.style.display="none";function fb(a,b){"insertRule"in gb?gb.insertRule(a+"{"+b+"}",0):gb.addRule(a,b)}var gb=document.createElement("style");gb.setAttribute("type","text/css");
if($a("head").length){$a("head")[0].appendChild(gb);gb=document.styleSheets[document.styleSheets.length-1];fb(".offscreen","position:absolute;top:-200%;right:-200%;visibility:hidden;");fb(".grid","top:50%");if(Ta){fb(".grid, .scroll-container","transition:transform cubic-bezier(0,0,0.25,1) 0.2s");za&&fb(".grid, .scroll-container",za+"transition:"+za+"transform cubic-bezier(0,0,0.25,1) 0.2s");if(Ma){fb(".grid, .scroll-container","backface-visibility:hidden");za&&fb(".grid, .scroll-container",za+"backface-visibility:hidden")}}};var hb=/^-?\d+(?:px)?$/i,ib=/^-?\d/;function jb(a,b){if(!a)return k;var c=a.k||a.k===0?a.k:a.b;return b.c>=(a.w||a.w===0?a.w:a.c)&&b.b>=c&&b.c<=a.Ka&&b.b<=a.T}function H(a,b){if(b&&hb.test(b))return parseFloat(b);return i}function kb(a){return document.defaultView.getComputedStyle(a,i)}function I(a){return a&&a.offsetHeight||0}function J(a){return a&&a.offsetWidth||0}function lb(a){return a&&a.offsetTop||0}
if(!(document.defaultView&&document.defaultView.getComputedStyle)){kb=function(a){return a.currentStyle};if(w){lb=function(a){if(a){a.style.zoom=1;return a.offsetTop}return 0};I=function(a){if(a){a.style.zoom=1;return a.offsetHeight}return 0};J=function(a){if(a){a.style.zoom=1;return a.offsetWidth}return 0}}H=function(a,b){var c,d,e;if(b&&hb.test(b))return parseFloat(b);else if(b&&ib.test(b)){c=a.style.left;d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b||0;e=a.style.pixelLeft;
a.style.left=c;a.runtimeStyle.left=d;return e}return i}}function K(a,b,c){a.style[b]=c+"px";return c}if(La)var mb=function(a,b){if("transformProperty"in a.style)a.style.transformProperty=b;else a.style[Aa+"Transform"]=b},pb=Ma?function(a,b,c){mb(a,"translate3d("+b+"px,"+c+"px,0)")}:function(a,b,c){mb(a,"translate("+b+"px,"+c+"px)")},qb=function(a,b){pb(a,b,0)};else{pb=function(a,b,c){K(a,"left",b);K(a,"top",c)};qb=function(a,b){K(a,"left",b)}}function rb(a,b){return Math.ceil(a)+b-a%b}
function L(a){if(a){var b=kb(a);a.getAttribute("style");var c;this.display=b.display;this.position=b.position;if(w)a.style.zoom=1;this.marginTop=H(a,b.marginTop)||0;this.marginBottom=H(a,b.marginBottom)||0;this.marginLeft=H(a,b.marginLeft)||0;this.marginRight=H(a,b.marginRight)||0;this.marginHeight=this.marginTop+this.marginBottom;this.marginWidth=this.marginLeft+this.marginRight;this.borderTop=H(a,b.borderTopWidth)||0;this.borderBottom=H(a,b.borderBottomWidth)||0;this.borderLeft=H(a,b.borderLeftWidth)||
0;this.borderRight=H(a,b.borderRightWidth)||0;this.paddingTop=H(a,b.paddingTop)||0;this.paddingBottom=H(a,b.paddingBottom)||0;this.paddingLeft=H(a,b.paddingLeft)||0;this.paddingRight=H(a,b.paddingRight)||0;this.D=this.borderTop+this.paddingTop;this.ga=this.borderBottom+this.paddingBottom;this.X=this.D+this.ga;this.Sb=this.borderLeft+this.paddingLeft;this.Tb=this.borderRight+this.paddingRight;this.Va=this.Sb+this.Tb;this.oa=J(a);this.m=I(a);this.c=this.oa-this.Va;this.b=this.m-this.X;this.w=H(a,b.minWidth)||
0;this.k=H(a,b.minHeight)||0;c=H(a,b.maxWidth);this.Ka=!c||c===-1?Infinity:c;c=H(a,b.maxHeight);this.T=!c||c===-1?Infinity:c;this.lineHeight=H(a,b.lineHeight)||i}}L.prototype.F=function(){var a=new L,b;for(b in this)if(a[b]!==this[b])a[b]=this[b];return a};function M(a,b,c){var d=document.createEvent("UIEvents"),e;d.initEvent(b,k,g);if(c)for(e in c)d[e]=c[e];return a.dispatchEvent(d)}function N(a,b,c){a.addEventListener(b,c,k)}function Q(a,b,c){a.removeEventListener(b,c,k)}
if(!("addEventListener"in document)||document.documentMode===9){var sb=["abort","activate","afterprint","afterupdate","beforeactivate","beforecopy","beforecut","beforedeactivate","beforeeditfocus","beforepaste","beforeprint","beforeunload","beforeupdate","blur","bounce","cellchange","change","click","contextmenu","controlselect","copy","cut","dataavailable","datasetchanged","datasetcomplete","dblclick","deactivate","drag","dragend","dragenter","dragleave","dragover","dragstart","drop","error","error",
"errorupdate","filterchange","finish","focus","focusin","focusout","hashchange","help","keydown","keypress","keyup","layoutcomplete","load","losecapture","message","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","mousewheel","move","moveend","movestart","offline","online","page","paste","progress","propertychange","readystatechange","readystatechange","reset","resize","resizeend","resizestart","rowenter","rowexit","rowsdelete","rowsinserted","scroll","select","selectionchange",
"selectstart","start","stop","storage","storagecommit","submit","timeout","unload"],tb=function(){this.returnValue=k},ub=function(){this.cancelBubble=g};M=function(a,b,c){var d=document.createEventObject(),e;d.type=b;if(c)for(e in c)d[e]=c[e];if(!d.preventDefault)d.preventDefault=tb;if(!d.stopPropagation)d.stopPropagation=ub;try{return a.fireEvent("on"+b,d)}catch(f){}a.p&&a.p[b]&&a.p[b].jb(d);return k};var vb=function(a,b){return function(c){c=c||window.event;c.target=c.target||c.srcElement;c.preventDefault=
tb;c.stopPropagation=ub;a.p[b].ua.forEach(function(d){try{"handleEvent"in d?d.handleEvent(c):d.call(a,c)}catch(e){}})}};N=function(a,b,c){if(!a.p)a.p={};if(!a.p[b]){a.p[b]={ua:[],jb:vb(a,b)};sb.indexOf(b)!==-1&&a.attachEvent("on"+b,a.p[b].jb)}a.p[b].ua.push(c)};Q=function(a,b,c){if(a.p&&a.p[b]){c=a.p[b].ua.indexOf(c);c!==-1&&a.p[b].ua.remove(c);if(!a.p[b].ua.length){sb.indexOf(b)!==-1&&a.detachEvent("on"+b,a.p[b].jb);a.p[b]=i}}}}ca("treesaver.addListener",N,void 0);
ca("treesaver.removeListener",Q,void 0);function wb(a,b,c){this.fa=a;this.t=b;this.g=c}var xb=new wb(Infinity,Infinity,Infinity);function yb(a,b){if(a.fa!==b.fa)return b.fa-a.fa;else if(a.g!==b.g)return a.g-b.g;return b.t-a.t}wb.prototype.F=function(){return new this.constructor(this.fa,this.t,this.g)};function zb(){this.g=this.f=this.index=0;this.I=k;this.s=[];this.ka=[];this.Aa=0}zb.prototype.F=function(){var a=new this.constructor;a.index=this.index;a.f=this.f;a.g=this.g;a.I=this.I;a.s=this.s.slice(0);a.ka=this.ka.slice(0);a.Aa=this.Aa;return a};
function Ab(a,b){if(a.g)return k;var c,d,e;c=a.index;for(d=b.i.length;c<d;c+=1){e=b.i[c];if(!e.wa)return k;if(!Bb(a,c)&&!e.t.da)return k}if(!a.s.length&&a.f===b.l.length)return g;for(c=a.s.slice(0);c.length;){e=b.l[c.pop()];if(!e.da)return k}c=a.f;for(d=b.l.length;c<d;c+=1){e=b.l[c];if(!e.da)return k}return g}function Cb(a,b){var c;if(b<a.f)if((c=a.s.indexOf(b))!==-1)a.s.remove(c);else{if((c=a.ka.indexOf(b))!==-1)a.ka.remove(c)}else{if(b>a.f)for(;a.f<b;a.f+=1)a.s.push(a.f);a.f=b+1}}
function Db(a,b){if(a.s.indexOf(b)===-1){Cb(a,b);a.s.push(b)}}function Bb(a,b){if(a.f<=b)return k;if(a.s.indexOf(b)!==-1)return k;if(a.ka.indexOf(b)!==-1)return k;return g};function Eb(a,b,c,d){this.j=a;this.w=parseInt(b||0,10);this.k=parseInt(c||0,10);this.C=d}Eb.prototype.ca=function(){if(!this.C)return g;return Ya(this.C,g)};function Fb(a,b,c){c&&C(b,c);b.innerHTML=a.j;ab("data-src",i,"img",b).forEach(function(d){d.setAttribute("src",d.getAttribute("data-src"))})};if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")};if(!Object.ya)Object.ya=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(c);return b};if(!Object.db)Object.db=function(a){return Object.prototype.toString.apply(a)==="[object Object]"};Object.F=function(a){function b(){}b.prototype=a;return new b};function Gb(a,b){Hb(a,b)}
function Hb(a,b){var c=[],d=[],e,f,h,o;c=ab("data-bind",i,i,b);e=0;for(h=c.length;e<h;e+=1){o=k;for(f=0;f<h;f+=1)if(c[e]!==c[f]&&c[f].contains(c[e])){o=g;break}o||d.push(c[e])}G(b,"data-bind")&&d.push(b);d.forEach(function(l){l.getAttribute("data-bind").split(/\s+/).forEach(function(j){var s=j.indexOf(":"),r=i,n=i,p=i,x=[],y="";if(s!==-1){r=j.substring(0,s);n=j.substring(s+1)}else r=j;if(a[r]){p=a[r];if(Array.Bb(p)){x=u(l.childNodes);p.forEach(function(t){x.forEach(function(z){z=z.cloneNode(g);z.nodeType===
1&&Hb(t,z);l.appendChild(z)})});x.forEach(function(t){l.removeChild(t)})}else if(Object.db(p)){x=u(l.childNodes);x.forEach(function(t){t.nodeType===1&&Hb(p,t)})}else{if(n!==i)if((n==="href"||n==="src")&&G(l,"data-"+n)){if(!(G(l,n)&&/{{[^}]+}}/.test(y=l.getAttribute(n))))y=l.getAttribute("data-"+n)}else y=n==="class"?l.className:l.getAttribute(n);else y=l.innerHTML;p||(p="");p=p.toString();y=y&&/{{[^}]+}}/.test(y)?y.replace(/{{([^}]+)}}/g,function(t,z){z=z.trim();return z===r?n!==i&&(n==="href"||n===
"src")?encodeURIComponent(p):n?p:Ib(p):"{{"+z+"}}"}):Ib(p);if(n)if(n==="class")l.className=y;else l.setAttribute(n,y);else l.innerHTML=y}}})})}function Jb(a,b){return a.getAttribute("data-bind").split(/\s+/).some(function(c){var d=c.indexOf(":");return d!==-1?c.substring(0,d)===b:c===b})}function Kb(a,b,c){return ab("data-bind",i,b,c).filter(function(d){return Jb(d,a)})}
function Ib(a){return a.replace(/&(?!\w+;)|[<>]/g,function(b){switch(b){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";default:return b}})};function Lb(a,b,c){this.rc=c.index;this.f=c.f;c.f+=1;this.la=i;this.q={};this.da=!D(a,"required");this.Nb=D(a,"zoomable");this.nc=[];u(a.childNodes).forEach(function(d){if(d.nodeType!==1)d.data&&d.data.trim();else a:{var e=d.getAttribute("data-sizes"),f=parseInt(d.getAttribute(G(d,"width")?"width":"data-minwidth"),10),h=parseInt(d.getAttribute(G(d,"height")?"height":"data-minheight"),10),o=G(d,"data-requires")?d.getAttribute("data-requires").split(" "):i;if(o)if(!Ya(o))break a;d.removeAttribute("hidden");
Za(d,"hidden");d=cb(d);e=e?e.split(" "):["fallback"];Mb(this,e,d,f,h,o)}},this);if(this.q.fallback){Nb(this,this.q.fallback[0].j,a,b,c);delete this.q.fallback}delete this.nc}
function Nb(a,b,c,d,e){var f=c.parentNode,h=document.createElement("div");h.innerHTML=b;b=b=h.childNodes.length===1?h.firstChild:h;f.insertBefore(b,c);if(a.Nb){C(b,"zoomable");b.setAttribute("data-figureindex",a.f);Da&&b.setAttribute("onclick","void(0)")}Ob(b,d);a.la=new Pb(b,d,e,g);a.la.t=a;a.la.i&&a.la.i.forEach(function(o){o.t=this;o.Mb=g},a);f.removeChild(b)}
function Sb(a,b){var c=-Infinity,d=-Infinity,e,f;for(f in a.q)a.q[f].forEach(function(h){if(h.ca())if(!(h.w&&h.w>b.c||h.k&&h.k>b.b))if((!h.w||h.w>=c)&&(!h.k||h.k>=d)){c=h.w;d=h.k;e={name:f,Ha:h}}});return e}function Mb(a,b,c,d,e,f){var h=new Eb(c,d,e,f);b.forEach(function(o){if(this.q[o])this.q[o].push(h);else this.q[o]=[h]},a)}function Tb(a){var b=a.nodeName.toLowerCase();return a.nodeType===1&&b==="figure"};function Pb(a,b,c,d){var e=Ub(a),f,h="";if(a.nodeType!==1)this.va=g;else{a=a;if(I(a)){this.index=c.index;c.index+=1;this.aa=!e&&Vb(a);this.$=this.Mb=this.wa=k;this.t=i;this.i=[];this.l=[];f=k;if(this.aa&&!D(a,"keeptogether")){Wb(this,a,b,c,d);f=!!this.l.length;this.aa=!!this.i.length}this.Wa=this.Wa||!e;this.$b=D(a,"keepwithnext");this.Ub=D(a,"columnbreak");this.ma=this.ma||!this.Wa||D(a,"keeptogether");this.d=new L(a);if(!this.d.lineHeight)this.d.lineHeight=b;if(!this.ma)this.ma=this.d.X+this.d.lineHeight===
this.d.m;this.ra=this.ma?this.d.m:!this.aa?this.d.D+this.d.lineHeight:!this.$?this.d.D+this.i[0].ra+(this.d.D?this.i[0].d.marginTop:0):this.d.D+this.i[0].ra;this.j=cb(a);this.lb=this.aa?this.j.substr(0,this.j.indexOf(">")+1):i;this.Xa=this.aa?this.j.slice(this.j.lastIndexOf("<")):i;if(f){this.j=this.lb;this.i.forEach(function(o){this.j+=o.j},this);this.j+=this.Xa}if(this.aa){a=a.cloneNode(g);this.d.marginTop&&K(a,"marginTop",0);this.d.borderTop&&K(a,"borderTopWidth",0);this.d.paddingTop&&K(a,"paddingTop",
0);h=cb(a)}this.ec=this.aa?h.substr(0,h.indexOf(">")+1):i}else this.va=g}}function Xb(a){return a.nextSibling?a.nextSibling:a.parent?Xb(a.parent):i}
function Wb(a,b,c,d,e){var f,h=a instanceof Pb,o=b.nodeName.toLowerCase()==="ol"&&"start"in b,l=o?b.start:i;if(l===-1)l=1;u(b.childNodes).forEach(function(j){if(o&&j.nodeName.toLowerCase()==="li"){if(j.value&&j.value!==-1)l=j.value;j.setAttribute("value",l);l+=1}if(Tb(j)){if(e)return;j=new Lb(j,c,d);a.l.push(j);if(j=j.la){j.wa=g;if(h)a.$=g}}else{j=new Pb(j,c,d,!!e);if(h&&!a.$)a.$=j.$}if(j&&!j.va){a.i=a.i.concat(j,j.i||[]);if(j.l.length){a.l=a.l.concat(j.l);delete j.l}j.parent=h?a:i;if(f)f.nextSibling=
j;f=j}})}function Yb(a,b){for(var c=a.parent,d=[];c;){d.unshift(b?c.ec:c.lb);c=c.parent}return d.join("")}function Zb(a){a=a.parent;for(var b=[];a;){b.push(a.Xa);a=a.parent}return b.join("")}
function Vb(a){if($b(a))return k;if(ac(a))return g;var b,c,d,e=k;b=0;for(c=a.childNodes.length;b<c;b+=1){d=a.childNodes[b];if(d.nodeType===3&&/[^\s]/.test(d.data))return k;else if(d.nodeType===1){if($b(d)||ac(d))return g;e=g;d=kb(d);if(/inline/.test(d.display))return k;else if(/block/.test(d.display))return g}}return e}var bc=["img","video","object","embed","iframe","audio","canvas","svg","table"];function Ub(a){var b=a.nodeName.toLowerCase();return a.nodeType===1&&bc.indexOf(b)!==-1}
var cc=["p","h1","h2","h3","h4","h5","h6"];function $b(a){var b=a.nodeName.toLowerCase();return a.nodeType===1&&cc.indexOf(b)!==-1}var dc=["div","article","ul","ol","figure","aside"];function ac(a){var b=a.nodeName.toLowerCase();return a.nodeType===1&&dc.indexOf(b)!==-1}
function Ob(a,b){if(a.nodeType!==1)return a;var c,d;a.removeAttribute("id");if(Tb(a))return a;if(Vb(a)&&!D(a,"keeptogether"))for(c=a.childNodes.length-1;c>=0;c-=1){d=a.childNodes[c];d.nodeType!==1?a.removeChild(d):Ob(d,b)}if(!window.TS_NO_AUTOMETRICS){c=new L(a);c.marginTop%b&&K(a,"marginTop",rb(c.marginTop,b));c.marginBottom%b&&K(a,"marginBottom",rb(c.marginBottom,b));if(Ub(a)||D(a,"keeptogether"))c.m%b&&K(a,"paddingBottom",c.paddingBottom+b-c.m%b);else{if(c.lineHeight)c.lineHeight%b&&K(a,"lineHeight",
rb(c.lineHeight,b));else{c.lineHeight=b;K(a,"lineHeight",b)}c.D%b&&K(a,"paddingTop",rb(c.D,b)-c.borderTop);if(c.ga%b)c.paddingBottom=K(a,"paddingBottom",rb(c.ga,b)-c.borderBottom);c.m=I(a);if(c.m%b){c.paddingBottom+=b-c.m%b;K(a,"paddingBottom",c.paddingBottom)}}}return a};function ec(a){var b={},c;if(a.properties){c=Object.ya(a.properties);c.forEach(function(d){var e=a.properties[d][0];if(Object.db(e))e=ec(e);b[d]=e})}return b}
function fc(a){this.lineHeight=H(a,kb(a).lineHeight)||1;this.Z=a.offsetWidth;$a("figure",a).forEach(function(b){b.style.display="none"});Ob(a,this.lineHeight);this.l=[];this.i=[];Wb(this,a,this.lineHeight,{index:0,f:0});this.H={};gc(i,a).forEach(function(b){var c=ec(b);Object.ya(c).forEach(function(d){this.H[d]||(this.H[d]=c[d])},this)},this)};function hc(a,b){var c=new L(a);this.u=!D(a,"fixed");(this.k=c.k)&&K(a,"minHeight",0);this.b=c.m;this.Fa=Math.max(0,b-this.b)}hc.prototype.Ca=function(a){if(!this.u)return this;this.b=Math.max(0,a-this.Fa);return this};function ic(a,b){var c=new L(a);this.u=!D(a,"fixed");(this.k=c.k)&&K(a,"minHeight",0);this.b=c.m;this.Fa=Math.max(0,b-this.b);this.q=(c=a.getAttribute("data-sizes"))?c.split(" "):[]}ic.prototype.Ca=function(a){if(!this.u)return this;this.b=Math.max(0,a-this.Fa);return this};function jc(a){document.body.appendChild(a);this.C=G(a,"data-requires")?a.getAttribute("data-requires").split(" "):i;var b;b=a.className?a.className.toLowerCase().split(/\s+/):[];this.xb=b;this.u=!D(a,"fixed");kc(this);this.Da=this.size=new L(a);if(this.u)this.size.w=Math.max(this.size.w||0,this.size.c);else{this.size.k=this.size.b;this.size.w=this.size.c}this.lineHeight=this.size.lineHeight||1;this.Z=this.ba=this.W=0;this.error=k;this.cols=[];E("column",a).forEach(function(c){var d=new hc(c,this.size.b);
this.cols.push(d);this.W+=d.b;this.ba=Math.max(this.ba,d.b);if(this.Z){if(this.Z!==c.offsetWidth)this.error=g}else this.Z=c.offsetWidth},this);this.G=[];E("container",a).forEach(function(c){this.G.push(new ic(c,this.size.b))},this);this.j=cb(a);document.body.removeChild(a)}var lc={onlypage:g,odd:g,even:g,sizetocontainer:g},mc=/^(no-)?page-(\d+)$/;
function kc(a){var b=k,c,d;a.K={};a.Ma={};a.Eb={};a.xb.forEach(function(e){if(e in lc)this.K[e]=g;else if(c=mc.exec(e)){d=parseInt(c[2],10);if(!isNaN(d))if(e.substr(0,3)==="no-")this.Eb[d]=g;else{b=g;this.Ma[d]=g}}},a);if(!b)a.Ma=i}
jc.prototype.Ca=function(a){if(!this.u)return this;var b=Math.min(this.size.T,Math.max(a-(this.size.marginHeight+this.size.X),this.size.k));b-=(b-this.size.k||0)%this.lineHeight;this.W=this.ba=0;this.cols.forEach(function(c){this.W+=c.Ca(b).b;this.ba=Math.max(this.ba,c.b)},this);this.G.forEach(function(c){c.Ca(b)},this);this.Da=this.size.F();this.Da.b=b;this.Da.m=b+this.size.X;this.Da.T=this.K.sizetocontainer?this.size.T:Math.min(this.size.T,b+this.lineHeight*3);return this};
function nc(a,b){return b.size.c+20*b.G.length-(a.size.c+20*a.G.length)}
function oc(a,b,c){var d=i,e=-Infinity,f,h,o=a.i.length,l,j,s,r,n,p,x,y,t,z,F,O,Z;s=0;r=b.length;for(;s<r;s+=1){n=b[s];O=0;Z=k;f=c.F();x=f.g;y=n.W-x;if(x&&n.W)Z=g;p=0;h=f.Aa+1;p+=n.cols.length*50;if(n.lineHeight!==a.lineHeight)p-=2E3;if(n.Z&&n.Z!==a.Z)p-=Infinity;if(n.K.onlypage)p+=f.Aa?-Infinity:4E3;if(n.Ma)if(n.Ma[h])p+=3E3;else p-=Infinity;if(n.Eb[h])p-=Infinity;p+=h%2?n.K.odd?2E3:n.K.even?-Infinity:0:n.K.even?2E3:n.K.odd?-Infinity:0;p=p;h=n;l=a;j=f;t=void 0;z=void 0;F=void 0;var q=void 0,$=void 0,
P=void 0,aa=void 0,Qb=void 0,V=void 0,nb=void 0,Vc=void 0,Rb=[];t=0;z=h.G.length;for(;t<z;t+=1){F=h.G[t];Rb[t]=i;P=j.f;nb=j.s.slice(0);c:for(;nb.length||P<l.l.length;){aa=(Vc=!!nb.length)?nb.shift():P;Qb=l.l[aa];q=F.q.length-1;d:for(;q>=0;q-=1){$=F.q[q];e:{V=Qb;var ob=$,Oa=void 0,Wc=void 0;if(V.q[ob]){Oa=0;for(Wc=V.q[ob].length;Oa<Wc;Oa+=1)if(V.q[ob][Oa].ca()){V=V.q[ob][Oa];break e}}V=i}if(V){if(F.u&&V.k&&V.k>F.b)continue d;Rb[t]={f:aa,Ha:V,size:$,u:F.u};Cb(j,aa);break c}}if(!Qb.da)break;Vc||(P+=
1)}}h=Rb;j=0;t=h.length;for(;j<t;j+=1){z=n.G[j];if(F=h[j]){l=a.l[F.f];p+=2E3+F.Ha.k*5;l.da||(p+=4E3);z.u||(p+=5E3);O+=1}else z.u||(p-=5E3)}b:for(;n.W&&f.index<o&&x<=n.W;){l=a.i[f.index];j=l.d.m+l.d.marginTop;if(l.ma&&(j>n.ba||j>y))break b;if(j>y){if(l.ma)break b;if(l.children){f.index+=1;continue b}x+=j}x+=j;p+=j;y-=j;Z=g;f.index=l.nextSibling?l.nextSibling.index:f.index+1}if(Z){if(y>0){f=y/n.W;f-=O*0.2;if(f>0.5){p-=y;p-=f*f*2E3}}}else if(O){if((l=a.i[f.index])&&l.t&&!l.t.da)if(f.g||l.Mb)p=-Infinity}else p=
-Infinity;if(p>e){e=p;d={N:n,G:h}}}return d};function pc(a,b,c){var d=oc(a,b,c);b=document.createElement("div");var e=c.F(),f=k;if(!d||!d.N){c.I=Ab(c,a)||c.f===a.l.length;if(c.I)this.va=g;else this.error=g}else{this.size=d.N.Da.F();this.vb=new wb(c.index,c.f,c.g);C(b,"offscreen");document.body.appendChild(b);b.innerHTML=d.N.j;this.a=b.firstChild;K(this.a,"width",this.size.c);K(this.a,"height",this.size.b);Object.ya(a.H||{}).forEach(function(h){Kb(h,i,this.a).forEach(function(o){var l={};l[h]=a.H[h];Hb(l,o)})},this);E("container",this.a).forEach(function(h,
o){var l=d.G[o],j,s,r;if(l){s=l.f;j=a.l[s];var n=a.lineHeight,p,x,y;r=g;p=l.size;x=l.Ha;y=I(h);Fb(x,h,p);if(l.u){if(D(h,"bottom")){r=k;h.style.top="auto"}else h.style.bottom="auto";l=I(h);if(l>y){Za(h,p);bb(h);r=k}else{if(n&&l%n)l=rb(l,n);for(n=h;n=n.nextSibling;)if(n.nodeType===1)if(!D(n,"fixed"))if(D(n,"column")||D(n,"container")||D(n,"group")){C(n,"flexed");if(I(n)<=l)K(n,"height",0);else r?K(n,"top",lb(n)+l):K(n,"bottom",I(n.offsetParent)-(lb(n)+I(n))+l)}r=g}}else r=g;if(r){Cb(c,s);f=g;if(j.Nb){C(h,
"zoomable");h.setAttribute("data-figureindex",s);Da&&h.setAttribute("onclick","void(0)")}if(o===0&&d.N.K.sizetocontainer){this.size.b=I(h)+d.N.G[0].Fa;this.size.m=this.size.b+this.size.X;K(this.a,"height",this.size.b)}}else{if(!j.da&&j.la)Db(c,j.f);else if(!D(h,"flexed")){Cb(c,s);c.ka.push(s)}h.parentNode.removeChild(h)}}else h.parentNode.removeChild(h)},this);E("column",this.a).forEach(function(h,o){var l=d.N.ba,j=d.N.cols[o].k,s=I(h),r=0,n,p,x=g,y=0,t=0,z=0,F=0,O=[],Z=a.i.length,q=a.i[c.index],
$,P;t=[];var aa;t=k;l=l/s>1.5;if(q){if(s%a.lineHeight)s-=s%a.lineHeight;if(!(!s||s<j)){q.parent&&O.push(Yb(q,g));y=c.g?q.d.m-c.g:0;a:for(;c.index<Z&&r<s;){q=a.i[c.index];P=($=q.nextSibling)||Xb(q);if(q.wa&&Bb(c,q.t.f)&&!(x&&c.g)){c.index=P?P.index:Z;continue a}j=q.parent;n=s-r;if(x&&!z){z=-y;t=c.overflow?q.d.lineHeight:q.ra}else{z=Math.max(z,q.d.marginTop);t=z+q.ra}F=Math.max(q.d.marginBottom,$?$.d.marginTop:0);aa=q.d.m+z;t=n<t;if(!t&&q.$b&&$&&!(c.g||x&&!l))t=n>=aa&&n<aa+F+$.ra;if(t)t=!x||l;if(t)t=
!q.$;if(q.Ub&&!x)t=g;if(t){if(j){for(;j&&j.index===q.index-1;){O.pop();c.index=j.index;j.wa&&Db(c,j.t.f);q=j;j=q.parent}j&&O.push(Zb(q))}break a}q.wa&&Cb(c,q.t.f);if(q.$||q.i.length&&n<aa){if(q.d.D){r+=x?0:z;z=0;r+=q.d.D}O.push(q.lb);c.index+=1;continue a}r+=aa;O.push(q.j);x=k;p=p||q;c.g=0;if(s>r+F){c.index=P?P.index:Z;if(!$&&j){t=[];do{t.push(j.Xa);if(j.d.ga){r+=F+j.d.ga;F=j.d.marginBottom}else F=Math.max(F,j.d.marginBottom)}while(!j.nextSibling&&(j=j.parent));if(s>r+F)O.push(t.join(""));else{j&&
O.push(Zb(q));r=s;break a}}z=F;continue a}j&&O.push(Zb(q));if(q.Wa){if(r<=s){c.index=P?P.index:Z;r=s}}else{r=s;c.index=P?P.index:Z}break a}x=q;s=s;r=r;if(s>=r||!x)c.g=0;else{c.g=r-s;r=c.g-x.d.ga;if(r<=0){c.g=0;c.index=x.index+1}else if(r=(x.d.b-r)%x.d.lineHeight){s-=r;c.g+=r}}K(h,"height",s);h.innerHTML=O.join("");if(p&&h.firstChild){h.firstChild.style.marginTop=-y+"px";if(p.parent&&!y){for(j=p.parent;j;){if(j.d.D)p=j;j=j.parent}if(j!==p){j=p.parent;for(q=h.firstChild;j;){q=q.firstChild;j=j.parent;
if(q)q.style.marginTop=0}}}else if(p.i.length&&!y)for(q=h.firstChild;p;)if(p.i.length&&q.firstChild){p=p.i[0];q=q.firstChild;q.style.marginTop=0}else p=i}else bb(h)}}});if(c&&c.index===e.index&&c.f===e.f&&c.g===e.g&&c.s.length===e.s.length)this.error=g;else if(!f&&d.N.K.sizetocontainer)this.va=g;else{K(this.a,"marginTop",-this.size.m/2);this.j=b.innerHTML;this.end=new wb(c.index,c.f,c.g);this.o=k;c.Aa+=1;c.I=d.N.K.onlypage||Ab(c,a)}b.removeChild(this.a);this.a=i;document.body.removeChild(b);b=i}}
pc.prototype.M=function(){if(this.o)return this.a;this.a=eb(this.j);this.o=g;return this.a};pc.prototype.A=function(){this.o=k;this.a=i};pc.prototype.F=function(){var a=Object.F(this);a.a=this.a&&this.a.cloneNode(g)||i;a.o=this.o;return a};var B={};B.Ob=1E4;B.ja={Qb:"treesaver.online",Pb:"treesaver.offline"};B.Lb=["offline","online"];B.Kb=["uncached","idle","checking","downloading","updateready","obsolete"];B.Ja=k;B.load=function(){if(!B.Ja){B.Ja=g;B.Lb.forEach(function(a){N(document,a,B)});Ka&&B.hb&&B.Kb.forEach(function(a){N(window.applicationCache,a,B)})}};B.oc=function(){if(B.Ja){B.Ja=k;B.Lb.forEach(function(a){Q(window,a,B)});Ka&&B.hb&&B.Kb.forEach(function(a){Q(window.applicationCache,a,B)})}};
B.xa=function(){if("onLine"in window.navigator)return window.navigator.onLine;return g};B.hb=Ka&&!!window.applicationCache.status;B.gb=function(){return B.hb};B.handleEvent=function(a){switch(a.type){case "online":Va();M(window,B.ja.Qb);break;case "offline":Va();M(window,B.ja.Pb);break;case "updateready":window.applicationCache.swapCache()}};
B.pc=function(a){var b,c;if(w){c=document.createElement("div");c.style.display="none";document.body.appendChild(c);c.innerHTML='<a href="'+a+'"></a>';b=c.firstChild}else{b=document.createElement("a");b.href=a}a=b.pathname;if(w){document.body.removeChild(c);c.removeChild(b)}if(a.charAt(0)!=="/")a="/"+a;return a};B.mc=function(a){var b=a.indexOf("#");return b===-1?a:a.substr(0,b)};B.gc=/^https?:\/\//i;
B.Ta=function(a){if(a&&a.charAt(0)==="/"||B.gc.test(a))return a;var b=document.createElement("a"),c;if(w){c=document.createElement("div");document.body.appendChild(c);c.appendChild(b)}b.href=a;a=b.href;if(w){document.body.removeChild(c);c.removeChild(b)}return a};B.ta=function(a,b,c){var d={L:new XMLHttpRequest,url:a,wb:b};la(function(){B.ic(d)},c||B.Ob,[],B.Db(d));d.L.onreadystatechange=B.Vb(d);try{d.L.open("GET",d.url,g);d.L.send(i)}catch(e){B.pb(d)}};B.Db=function(a){return"fetch:"+a.url};
B.Vb=function(a){return function(){if(a.L.readyState===4)if(a.L.status===0||a.L.status===200||a.L.status===304){a.wb(a.L.responseText,a.url);B.yb(a)}else B.pb(a)}};B.yb=function(a){qa(B.Db(a));a.L.onreadystatechange=i};B.pb=function(a){a.wb(i,a.url);B.yb(a)};B.ic=function(a){a.L.abort();B.pb(a)};function rc(a,b,c,d){this.content=this.pa=i;this.url=a;this.path=B.pc(a);this.title=b;this.Y=i;this.n=0;this.h=[];this.error=this.cc=this.ib=this.loaded=this.J=this.Ba=k;this.ia=this.na=i;this.bb=[];this.cb=c;d&&sc(this,d)}var tc=/<title>\s*(.+?)\s*<\/title>/i;
function sc(a,b){a.loaded=g;var c=document.createElement("div"),d=document.createElement("div"),e;e=(e=tc.exec(b))&&e[1]?e[1]:i;if(e)a.title=e;c.style.display="none";C(c,"offscreen grid");C(d,"column");document.body.appendChild(c);c.innerHTML=b;e=document.getElementById("ts_content")||$a("article",c)[0];if(!e){document.body.removeChild(c);a.error=g;return k}e.removeAttribute("id");bb(c);a.pa=e.getAttribute("data-theme")||e.getAttribute("data-grids")||i;if(a.pa){C(c,a.pa);C(d,a.pa);uc(a,a.cb)}for(;e.firstChild;)d.appendChild(e.firstChild);
c.appendChild(d);d.style.display="block";c.style.display="block";a.content=new fc(d);document.body.removeChild(c);c.removeChild(d);bb(d);vc(a);return g}function uc(a,b){a.cb=a.pa?b.filter(function(c){return c.xb.indexOf(this.pa)!==-1},a):b.slice(0)}function wc(a,b){a.bb=a.cb.filter(function(c){var d;d=c.C?Ya(c.C,g):g;return d&&jb(c.size,{c:b.c-c.size.Va,b:b.b-c.size.X-c.size.marginHeight})}).map(function(c){return c.Ca(b.b)});a.bb.sort(nc)}
function xc(a,b){if(!a.na||a.na.c!==b.c||a.na.b!==b.b){a.na=b;a.Ba=jb(a.ia,b)}return!a.Ba}function vc(a){qa("paginate");a.h=[];a.n=0;a.na&&wc(a,a.na);a.Y=new zb;a.ia=i;a.Ba=g;a.J=k}
rc.prototype.fc=function(a,b,c){qa("paginate");var d;for(b=b||0;!this.Y.I;){d=new pc(this.content,this.bb,this.Y);if(d.va){if(this.Y.I)break}else{if(d.error){if(this.Y.I)break;this.error=g;M(document,"treesaver.paginationerror",{Q:this});this.Y.I=g;break}this.h.push(d);this.n+=1;this.error=k;var e=this.ia,f=d.size;e=e||{};f=f||{};var h=f.X||(f.m?f.m-f.b:0),o=f.Va||(f.oa?f.oa-f.c:0);this.ia={c:Math.max(e.c||0,f.c+o||0),b:Math.max(e.b||0,f.b+h||0),Ka:Math.min(e.Ka||Infinity,f.Ka+o||Infinity),T:Math.min(e.T||
Infinity,f.T+h||Infinity)};if(!(b&&this.n<=b||c&&(c===xb||!(yb(c,d.end)>=0))))if(!this.Y.I){if(a){M(document,"treesaver.paginationprogress",{Q:this});yc(this,u(arguments))}return}}}this.J=g;M(document,"treesaver.paginationprogress",{Q:this,sc:g})};function yc(a,b){la(rc.prototype.fc,200,b,"paginate",a)}
function zc(a,b,c){a.Ba||vc(a);var d=[],e=b>=0?b+c-1:Infinity;!a.J&&e>a.h.length-1&&yc(a,[g,e]);if(a.J)c=Math.min(c,a.n-(b>=0?b:b-1));else{d.length=c;if(b<0)return d}if(b<0)for(e=-b;e<=c;e+=1)d[e+b]=a.h[a.n-e];else for(e=b;e<b+c;e+=1)d[e-b]=a.h[e];return d}
function Ac(a,b){if(!a.content)return-1;var c,d;if(!b||!b.fa&&!b.t&&!b.g)return 0;a.Ba||vc(a);if(!a.J)if(b===xb||!a.n||!(yb(b,a.h[a.n-1].end)>=0)){yc(a,[g,i,b]);return-1}if(b===xb)return a.J?a.n-1:-1;c=0;for(d=a.n;c<d;c+=1)if(yb(a.h[c].end,b)<0)return c;return a.J?a.n-1:-1};if(!Ga){var Bc=function(a){var b=[],c=[],d=[];d=[];d=u(a.childNodes);b=d.filter(function(e){return e.nodeType===1});if(G(a,"itemref")){d=a.getAttribute("itemref").trim().split(/\s+/);d.forEach(function(e){(e=document.getElementById(e))&&b.push(e)})}b=b.filter(function(e,f){var h=i,o=e,l=[];if(b.indexOf(e)!==f&&b.indexOf(e,f)!==-1)return k;for(;(o=o.parentNode)!==i&&o.nodeType===1;){l.push(o);if(G(o,"itemscope")){h=o;break}}if(h!==i){if(b.indexOf(h)!==-1)return k;return!l.some(function(j){var s=-1,
r=i;if((s=b.indexOf(j))!==-1){for(j=b[s];(j=j.parentNode)!==i&&j.nodeType===1;)if(G(j,"itemscope")){r=j;break}if(r===h)return g}return k})}return g});for(b.sort(function(e,f){return 3-((f.compareDocumentPosition?f.compareDocumentPosition(e):f.contains?(f!=e&&f.contains(e)&&16)+(f!=e&&e.contains(f)&&8)+(f.sourceIndex>=0&&e.sourceIndex>=0?(f.sourceIndex<e.sourceIndex&&4)+(f.sourceIndex>e.sourceIndex&&2):1)+0:0)&6)});a=b.pop();){if(G(a,"itemprop")){c.push(a);if(G(a,"itemscope")){a.itemScope=g;a.properties=
Bc(a)}}if(!G(a,"itemscope")){d=u(a.childNodes).reverse();d.forEach(function(e){e.nodeType===1&&b.push(e)})}}c.forEach(function(e){var f;if(G(e,"itemscope"))f=e;else{f=e.nodeName;f=f==="META"?e.content:["AUDIO","EMBED","IFRAME","IMG","SOURCE","VIDEO"].indexOf(f)!==-1?e.src:["A","AREA","LINK"].indexOf(f)!==-1?e.href:f==="OBJECT"?e.data:f==="TIME"&&G(e,"datetime")?e.dateTime:"textContent"in e?e.textContent:e.innerText}e.itemValue=f;e.itemProp=e.getAttribute("itemprop")});return c};document.getItems=
function(a,b){var c=[];a=a&&/\S/.test(a)?a.trim().split(/\s+/):[];c=ab("itemscope",i,i,b);return c=c.filter(function(d){if(!G(d,"itemprop"))if(a.length===0||G(d,"itemtype")&&a.indexOf(d.getAttribute("itemtype"))!==-1){d.itemScope=g;d.properties=Bc(d);if(G(d,"itemid"))d.itemId=d.getAttribute("itemid");if(G(d,"itemref"))d.itemRef=d.getAttribute("itemRef");if(G(d,"itemtype"))d.itemType=d.getAttribute("itemtype");return g}return k})}}
function Cc(a){var b={},c={},d={};if(a.itemType)b.type=a.itemType;if(a.itemId)b.id=a.itemId;if(G(a,"data-properties")){a.getAttribute("data-properties").split(/\s+/g).forEach(function(e){d[e]=g});b.sa=d}a.properties.forEach(function(e){var f=e.itemValue,h=[];if(f.itemScope)f=Cc(f);h=e.itemProp.split(/\s+/g);h.forEach(function(o){c[o]||(c[o]=[]);c[o].push(f)})});b.properties=c;return b}
function Dc(a,b){if(Ga){var c=u(document.getItems(a));if(!b)return c;return c.filter(function(d){return b.contains(d)})}else return document.getItems(a,b)}function gc(a,b){return Dc(a,b).map(function(c){return Cc(c)})};var Ec,Fc,Gc;
function Hc(a){Gc=document.createElement("div");if(a){var b=document.createElement("div");b.style.display="none";document.documentElement.appendChild(b);b.innerHTML=a;u(b.childNodes).forEach(function(c){if(c.nodeType===1&&c.nodeName.toLowerCase()==="div")Gc.appendChild(c);else c.nodeType===1&&c.nodeName.toLowerCase()==="body"&&u(c.childNodes).forEach(function(d){d.nodeType===1&&d.nodeName.toLowerCase()==="div"&&Gc.appendChild(d)})});document.documentElement.removeChild(b);b.innerHTML=""}Ic()}
function Ic(){Ec=Jc;var a=Fc.slice(0);Fc=[];a.forEach(function(b){b()})}function Kc(a){return Gc?E(a,Gc):[]}var Jc=2;function Lc(a){return window.JSON.parse(a)}function Mc(a){return window.JSON.stringify(a)}if(!("JSON"in window)){Lc=function(a){try{return eval("("+a+")")}catch(b){}return i};Mc=function(){return""}};function Nc(a,b,c){c=c?window.localStorage:window.sessionStorage;c.getItem(a)&&c.removeItem(a);try{c.setItem(a,Mc(b))}catch(d){}}function Oc(a){return(a=window.sessionStorage.getItem(a)||window.localStorage.getItem(a))?Lc(a):i}function Pc(a){window.sessionStorage.getItem(a)&&window.sessionStorage.removeItem(a);window.localStorage.getItem(a)&&window.localStorage.removeItem(a)}
function Qc(a){var b=[],c,d,e,f;a=a||"";f=a.length;c=0;for(d=window.localStorage.length;c<d;c+=1)if((e=window.localStorage.key(c))&&(!a||a===e.substr(0,f)))b.push(window.localStorage.key(c));c=0;for(d=window.sessionStorage.length;c<d;c+=1){e=window.sessionStorage.key(c);if(b.indexOf(e)===-1&&(!a||a===e.substr(0,f)))b.push(e)}return b}function Rc(a,b){Qc(a).forEach(function(c){if(!b||b.indexOf(c)===-1)Pc(c)})}
if(!Ja){var Sc={};Nc=function(a,b){Sc[a]=b};Oc=function(a){return Sc[a]};Pc=function(a){delete Sc[a]};Qc=function(){return[]}};var R,S,T,U,Tc,Uc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd;function hd(a){S=R=i;T=-1;Uc=Tc=U=i;Xc=[];Yc={};Zc={};$c=[];ad=id();if(!ad)return k;jd();kd();bd=B.mc(document.location.href);if(cd=a){a=new rc(bd,document.title,ad,a);if(a.error)ld();else{Zc[bd]=a;md(a,i,0,g)}}nd.forEach(function(b){N(document,b,od)});window.onpopstate=pd;qd();return g}function id(){var a=[];Kc("grid").forEach(function(b){var c=b.getAttribute("data-requires");if(!c||Ya(c.split(" "))){b=new jc(b);b.error||a.push(b)}});return a}
function jd(){var a=Kc("loading")[0];a||(a=document.createElement("div"));document.body.appendChild(a);a.style.top="50%";K(a,"margin-top",-I(a)/2);document.body.removeChild(a);dd=cb(a);a=a.cloneNode(g);document.body.appendChild(a);ed=new L(a);document.body.removeChild(a)}
function kd(){var a=Kc("error")[0];a||(a=document.createElement("div"));document.body.appendChild(a);a.style.top="50%";K(a,"margin-top",I(a)/2);document.body.removeChild(a);fd=cb(a);a=a.cloneNode(g);document.body.appendChild(a);gd=new L(a);document.body.removeChild(a)}function rd(){ed=dd=$c=Zc=Yc=Xc=Tc=U=T=S=R=i;nd.forEach(function(a){Q(document,a,od)});window.onpopstate=i}var nd=["treesaver.loaded","treesaver.loadfailed","treesaver.paginationprogress"];
function od(a){if(a.type==="treesaver.paginationprogress")M(document,"treesaver.pageschanged");else if(a.type==="treesaver.loaded")M(document,"treesaver.pageschanged");else if(a.type==="treesaver.loadfailed"&&a.Q===R)if(B.xa())document.location=R.url}function pd(a){if(a.state){var b=a.state.index;b||b===0?md(Xc[b],a.state.position,b,g):sd(a.state.url)}else sd(bd)}
function qd(){var a;a=ab("rel","contents","link")[0];a=!a||a.getAttribute("rel").indexOf("self")!==-1?bd:B.Ta(a.href);a===bd&&!(B.gb()&&B.xa())?td(cd,a):B.ta(a,td)}
function td(a,b){var c=b===bd;if(a){Nc("cache:"+b,a,g);if(c&&B.gb())if(B.xa()){sc(R,a);M(document,"treesaver.pageschanged")}}else{a=Oc("cache:"+b);if(!a)return}var d=[];ud(a);$c.forEach(function(e){var f,h,o;if(e.sa.self){f=b;e.H.url=b}else f=B.Ta(e.H.url);h=Zc[f];o=Xc.length;if(!h){h=new rc(f,e.H.title||"",ad);Zc[f]=h}if(Yc[f])Yc[f].push(o);else{Yc[f]=[o];d.push("cache:"+f);if(f===bd)U=o}Xc.push(h)});Rc("cache:",d);M(document,"treesaver.tocupdated")}
function ud(a){var b=document.createElement("div"),c=[];b.className="offscreen";document.body.appendChild(b);b.innerHTML=a;c=gc(i,b);$c=c.map(function(d){var e=Object.ya(d.properties),f={H:{},sa:d.sa||{}};e.forEach(function(h){f.H[h]=d.properties[h][0]});return f});document.body.removeChild(b)}function vd(){if(T===-1){if(!S)if(wd(g))return g;return k}var a=T-1;if(a<0){if(wd(g))return g;return k}T=a;S=i;Tc=-1;M(document,"treesaver.pageschanged");return g}
function xd(){if(T===-1){if(S===xb)if(yd())return g;return k}var a=T+1;if(a>=R.n){if(R.J){if(yd())return g;return k}return k}T=a;S=i;Tc=1;M(document,"treesaver.pageschanged");return g}function wd(a,b){if(!U)return i;var c=U-1,d=Xc[c];return b?d:md(d,a?xb:i,c)}function zd(){return!!((U||U===0)&&U<Xc.length-1)}function yd(a){if(!zd())return i;var b=U+1,c=Xc[b];return a?c:md(c,i,b)}function sd(a){a=Ad(a);if(!a&&a!==0)return k;return md(Xc[a],i,a)}
function Bd(a,b){Tc=0;if(xc(R,a)){T=-1;Uc=0}var c=[],d,e,f=2*b+1,h;if(T===-1){T=Ac(R,S);if(T===-1){c.length=f;c[b]=Cd();return c}}e=T-b;if(e<0){if((d=wd(k,g))&&d.content&&d.J)c=zc(d,e,-e);else{d=0;for(h=-e;d<h;d+=1)c[d]=i}d=f+e;e=0}else d=f;c=c.concat(zc(R,e,d));if(d=f-c.length)if(e=yd(g))if(e.content)c=c.concat(zc(e,0,d));else{Dd(e);xc(e,a);c.length=f}d=b;for(h=c.length;d<h;d+=1)c[d]||(c[d]=R.error?{M:pc.prototype.M,A:pc.prototype.A,j:fd,size:gd}:Cd());if(!S||S===xb)if(c[b]&&c[b].vb)S=c[b].vb;if(!Uc)Uc=
R.ia?R.ia.c:0;for(d=0;d<c.length;d+=1)for(f=d+1;f<c.length;f+=1)if(c[d]===c[f])c[f]=c[d].F();return c}function Ad(a,b){var c=Yc[a],d,e;if(!c||!c.length)return i;else if(c.length===1)return c[0];else{for(d=c.length-1;d>=0;){e=c[d];if(e===U)break;if(e<U)return b&&d!==c.length-1?c[d+1]:e;d-=1}return e}}
function Dd(a){if(!a.ib){a.ib=g;var b=Oc("cache:"+a.url);if(b){sc(a,b);M(document,"treesaver.loaded",{Q:a})}B.ta(a.url,function(c){a.ib=k;if(c){if(b!==c){Nc("cache:"+a.url,c,g);sc(a,c);M(document,"treesaver.loaded",{Q:a})}}else if(!b){a.cc=g;M(document,"treesaver.loadfailed",{Q:a})}})}}
function md(a,b,c,d){if(!a)return k;if(R===a)if(c===U)return g;if(a.title)document.title=a.title;R=a;if(S!==b){S=b;T=-1}T=-1;if(a.loaded){if(a.error){if(B.xa())document.location=a.url;return k}}else Dd(a);if(c||c===0){Tc=U>c?-1:1;U=c}else{Tc=0;U=Ad(a.url)}d?Ed({index:c,url:a.url,position:b},a.title,a.path):Fd({index:c,url:a.url,position:b},a.title,a.path);M(document,"treesaver.pageschanged");M(document,"treesaver.articlechanged",{Q:a,url:a.url,path:a.path});return g}
function Cd(){return{M:pc.prototype.M,A:pc.prototype.A,j:dd,size:ed}};function Gd(a){this.a=a;this.Ea=a.firstChild}function Hd(a){a.Jb={c:J(a.a),b:I(a.a)};a.zb={c:J(a.Ea),b:I(a.Ea)};a.qb=a.qb||0;a.rb=a.rb||0;Id(a,0,0,g)}Gd.prototype.contains=function(a){return this.Ea.contains(a)};function Id(a,b,c,d){b={x:Math.max(0,Math.min(a.zb.c-a.Jb.c,a.qb+b)),y:Math.max(0,Math.min(a.zb.b-a.Jb.b,a.rb+c))};if(d){a.rb=b.y;a.qb=b.x}pb(a.Ea,-b.x,-b.y)}
function Jd(a){var b=document.createElement("div");C(b,"scroll-container");for(Da&&a.setAttribute("onclick","void(0)");a.firstChild;)b.appendChild(a.firstChild);a.appendChild(b)};function Kd(a){this.C=G(a,"data-requires")?a.getAttribute("data-requires").split(" "):i;E("scroll",a).forEach(Jd);this.Ra=[];this.a=i;this.j=a.parentNode.innerHTML;this.size=new L(a);delete this.size.c;delete this.size.b;this.za=i;this.o=k;this.h=this.ub=this.P=this.nb=this.n=this.mb=this.z=i;this.qa=k;this.kb=i;this.O=k;this.Na=this.Oa=this.La=this.nextPage=this.sidebar=this.Ya=this.v=i}
Kd.prototype.M=function(){var a=[];a=[];a=[];if(!this.o){this.o=g;this.a=eb(this.j);this.z=E("viewer",this.a)[0];this.mb=Kb("pagenumber",i,this.a);this.n=Kb("pagecount",i,this.a);this.nb=E("pagewidth",this.a);this.Ya=Kb("current-url",i,this.a);this.nextPage=E("next",this.a);this.La=E("nextArticle",this.a);this.Oa=E("prev",this.a);this.Na=E("prevArticle",this.a);this.Ra=E("scroll",this.a).map(function(b){return new Gd(b)});a=E("menu",this.a);if(a.length>0)this.kb=a[0];a=Kb("toc",i,this.a);if(a.length>=
1){this.P=a[0];this.ub=this.P.cloneNode(g)}a=E("sidebar",this.a);if(a.length>0)this.sidebar=a[0];this.h=[];Ld.forEach(function(b){N(document,b,this)},this);this.qa=k;Md(this)}return this.a};Kd.prototype.A=function(){if(this.o){Nd(this);this.o=k;Ld.forEach(function(a){Q(document,a,this)},this);this.Na=this.Oa=this.La=this.nextPage=this.sidebar=this.ub=this.P=this.Ya=this.kb=this.nb=this.n=this.mb=this.z=this.a=i;this.h.forEach(function(a){a&&a.A()});this.za=this.h=i}};
function Nd(){qa("selectPages");qa("animatePages")}var Ld=["treesaver.tocupdated","treesaver.pageschanged","treesaver.articlechanged","keydown","click","mousewheel","DOMMouseScroll"];Da?Ld.push("touchstart","touchmove","touchend","touchcancel"):Ld.push("mouseover");
Kd.prototype.handleEvent=function(a){switch(a.type){case "treesaver.pageschanged":return Od(this);case "treesaver.tocupdated":na(this.Hb,[],"updateTOC",this);return Od(this);case "treesaver.articlechanged":Pd(this,a);return Qd(this,a);case "mouseover":a.touches||Md(this);break;case "touchstart":return Rd(this,a);case "touchmove":if(this.e){a.stopPropagation();a.preventDefault();this.e.fb=m();this.e.ac=a.touches[0].pageX;this.e.bc=a.touches[0].pageY;this.e.Wb=this.e.fb-this.e.startTime;this.e.S=this.e.ac-
this.e.jc;this.e.Ga=this.e.bc-this.e.lc;this.e.ea=Math.min(a.touches.length,this.e.ea);this.e.sb=this.e.ea===1&&Math.abs(this.e.S)>=30;if(this.e.Qa)Id(this.e.Qa,this.e.S,-this.e.Ga);else if(this.e.sb){this.B=this.e.S;Sd(this,g)}else if(this.B){this.Ua=m();Sd(this,Ta)}else if(this.e.ea===2)this.e.Za=a.touches[1].pageX-this.e.kc}break;case "touchend":var b=this.e,c=k;pa();this.e=i;if(b){a.stopPropagation();a.preventDefault();if(b.Qa&&b.fb)Id(b.Qa,b.S,-b.Ga,g);else if(b.ea===1)if(b.fb){if(b.sb||b.Ga<=
-30)(c=b.sb&&b.S>0?vd():xd())?this.V():Md(this)}else{b=Td(a.target);c=this.O||this.z.contains(b);var d=document.createEvent("MouseEvents");d.initMouseEvent("click",g,g,a.view,1,a.changedTouches[0].screenX,a.changedTouches[0].screenY,a.changedTouches[0].clientX,a.changedTouches[0].clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,0,i);if(b.dispatchEvent(d)&&c)this.qa?this.V():Md(this);else c?this.V():Md(this);c=g}else if(b.ea===2)if(Math.abs(b.Za)>=30){if(b.S<0&&b.Za<0)c=yd();else if(b.S>0&&b.Za>0)c=
wd();c?this.V():Md(this)}if(!c){this.Ua=m();this.B=0;Sd(this,Ta)}}break;case "touchcancel":pa();this.e=i;break;case "keydown":a:if(this.O){Ud(this);a.preventDefault()}else if(!Vd(a)){switch(a.keyCode){case 34:case 39:case 40:case 74:case 32:xd();break;case 33:case 37:case 38:case 75:vd();break;case 72:wd();break;case 76:yd();break;default:c=void 0;break a}this.V();a.preventDefault()}return c;case "click":return this.click(a);case "mousewheel":case "DOMMouseScroll":if(Vd(a))b=g;else if(this.O){Ud(this);
a.preventDefault()}else{c=m();if(!(this.Cb&&c-this.Cb<1500)){this.Cb=c;c=a.wheelDelta?a.wheelDelta:a.detail?-a.detail:0;d=this.z.contains(Td(a.target));if(c&&d){a.preventDefault();a.stopPropagation();c>0?vd():xd();this.V()}}}return b}};function Vd(a){return a.ctrlKey||a.shiftKey||a.altKey||a.metaKey}
Kd.prototype.click=function(a){if(this.O){Ud(this);a.stopPropagation();a.preventDefault()}else{if(Vd(a))return g;if(!("which"in a&&a.which!==1||a.button)){var b=Td(a.target),c,d=k,e=d=c=k;if(D(this.a,"menu-active")){e=this.kb.contains(b);Za(this.a,"menu-active")}if(Wd(this))(d=this.sidebar.contains(b))||Za(this.a,"sidebar-active");if(this.h[0]&&this.h[0].a.contains(b)){vd();c=g}else if(this.h[2]&&this.h[2].a.contains(b)){xd();c=g}else for(d=this.h[1]&&this.h[1].a.contains(b);!c&&b&&b!==W;){if(d){if(D(b,
"zoomable"))c=Xd(this,b)}else if(D(b,"prev")){vd();c=g}else if(D(b,"next")){xd();c=g}else if(D(b,"prevArticle")){wd();c=g}else if(D(b,"nextArticle")){yd();c=g}else if(D(b,"menu")){e||C(this.a,"menu-active");c=g}else if(D(b,"sidebar")||D(b,"open-sidebar")){Wd(this)||C(this.a,"sidebar-active");c=g}else if(D(b,"close-sidebar"))if(Wd(this)){Za(this.a,"sidebar-active");c=g}if(!c&&b.href&&b.nodeName.toLowerCase()!=="img"){if(b.getAttribute("target")==="lightbox"){b=b.parentNode;continue}c=B.Ta(b.href);
if(!sd(c))return;c=g}b=b.parentNode}if(c){a.stopPropagation();a.preventDefault()}}}};function Td(a){if(a){if(a.nodeType!==1&&a.parentNode)a=a.parentNode||W}else a=W;return a}function Rd(a,b){if(W.contains(Td(b.target))){b.stopPropagation();b.preventDefault();if(a.O)Ud(a);else{a.e={startTime:m(),Wb:0,jc:b.touches[0].pageX,lc:b.touches[0].pageY,S:0,Ga:0,ea:b.touches.length};if(a.e.ea===2)a.e.kc=b.touches[1].pageX;a.Ra.forEach(function(c){if(c.contains(Td(b.target)))this.e.Qa=c},a);oa([],4E3)}}}
function Md(a){if(!a.qa){a.qa=g;C(a.a,"active");M(document,"treesaver.active")}var b=a.V,c=ga.idletimer;if(c)c.eb=m();else ka(b,5E3,1,i,k,"idletimer",a)}Kd.prototype.V=function(){if(this.qa){this.qa=k;Za(this.a,"active");M(document,"treesaver.idle")}qa("idletimer")};function Wd(a){return D(a.a,"sidebar-active")}
function Xd(a,b){var c;c=parseInt(b.getAttribute("data-figureindex"),10);c=isNaN(c)?i:R.content.l[c];if(!c)return k;a.V();if(!a.O){var d=Yd(),e=Zd,f,h,o,l=i;f=0;for(h=e.length;f<h;f+=1){o=e[f];if(o.ca()&&o.Ia(d)){l=o;break}}a.v=l;if(!a.v)return k;a.O=g;a.v.M();a.a.parentNode.appendChild(a.v.a)}a.v.a=a.v.a;K(a.v.a,"width",J(a.a));K(a.v.a,"height",I(a.a));d=a.v;c=Sb(c,{c:J(d.r),b:I(d.r)});e=J(d.r.offsetParent);f=I(d.r.offsetParent);d.r=d.r;if(d.o&&c){Fb(c.Ha,d.r,c.name);d.r.style.bottom="auto";d.r.style.right=
"auto";K(d.r,"left",(e-J(d.r))/2);K(d.r,"top",(f-I(d.r))/2);c=g}else c=k;if(!c){Ud(a);return k}return g}function Ud(a){if(a.O){a.O=k;a.a.parentNode.removeChild(a.v.a);a.v.A();a.v=i}}Kd.prototype.ca=function(){if(!this.C)return g;return Ya(this.C,g)};Kd.prototype.Ia=function(a){return jb(this.size,a)};function $d(a){a.za={c:J(a.z),b:I(a.z)}}function ae(a,b){K(a.a,"width",b.c);K(a.a,"height",b.b);a.za=i;$d(a);a.Ra.forEach(function(c){Hd(c)});if(R){Od(a);na(a.Hb,[],"updateTOC",a)}}
function Qd(a,b){a.Ya.forEach(function(c){Hb({"current-url":b.url},c)})}function Pd(a){if(a.P){var b=$c||[],c=Kb("article",i,a.P),d=0;b.forEach(function(e,f){if(!e.sa.hidden&&c[d]){f===U?C(c[d],"current"):Za(c[d],"current");d+=1}});a.Ra.forEach(function(e){Hd(e)})}}function be(a,b){a.mb.forEach(function(c){Hb({pagenumber:b},c)})}function ce(a,b){a.n.forEach(function(c){Hb({pagecount:b},c)})}function de(a,b){b&&a.nb.forEach(function(c){K(c,"width",b)},a)}
function ee(a,b,c){if(b.nodeName==="BUTTON")b.disabled=!c;else c?Za(b,"disabled"):C(b,"disabled")}function fe(a){if(a.nextPage){var b=T!==-1?T<R.n-1?g:R.J&&zd():S===xb?zd():k;a.nextPage.forEach(function(c){ee(this,c,b)},a)}}function ge(a){if(a.La){var b=zd();a.La.forEach(function(c){ee(this,c,b)},a)}}function he(a){if(a.Oa){var b=T!==-1?T>=1?g:!!U:!S&&!!U;a.Oa.forEach(function(c){ee(this,c,b)},a)}}function ie(a){if(a.Na){var b=!!U;a.Na.forEach(function(c){ee(this,c,b)},a)}}
function Od(a){na(a.Gb,[],"selectPages",a)}
Kd.prototype.Gb=function(){Nd(this);var a=Tc;je(this,a);var b=this.h[0],c=this.h[1],d=this.h[2],e,f=Math.max(c.size.marginRight,d?d.size.marginLeft:0),h=Math.max(c.size.marginLeft,b?b.size.marginRight:0),o=this.B;c.a.setAttribute("id","currentPage");e=(this.za.c-c.size.oa)/2-f;c=e+c.size.oa+f+h;this.U=[];this.U[1]=e;if(b){this.U[0]=e-(b.size.oa+b.size.marginLeft);b.a.setAttribute("id","previousPage")}if(d){this.U[2]=c-d.size.marginLeft;d.a.setAttribute("id","nextPage")}if(a!==0){this.Ua=m();this.B=
a===-1?d?this.U[1]-this.U[2]:0:b?this.U[1]-this.U[0]:0;if(o)this.B+=o}else if(!this.B)this.B=0;if(Ta&&this.B)this.B=0;Sd(this,Ta);be(this,T+1||1);ce(this,R.n||1);de(this,Uc);fe(this);ge(this);he(this);ie(this)};
Kd.prototype.Hb=function(){qa("updateTOC");if(this.P){var a=$c||[],b=this.ub.cloneNode(g),c=this.P.parentNode;a=a.filter(function(d){return!d.sa.hidden});a=a.map(function(d){return{article:d.H}});Gb({toc:a},b);c.replaceChild(b,this.P);this.P=b;M(document,"treesaver.articlechanged",{Q:R,url:R.url,path:R.path})}};
function je(a,b){var c=a.h;a.h=Bd(a.za,1);c.forEach(function(d){if(d)if(this.h.indexOf(d)===-1){d.a&&d.a.parentNode===this.z&&this.z.removeChild(d.a);d.A()}},a);a.h.forEach(function(d){if(d){d.a||d.M();if(d.a.parentNode!==this.z)b===-1?this.z.insertBefore(d.a,this.z.firstChild):this.z.appendChild(d.a)}},a)}
function Sd(a,b){var c=a.B;if(!b){oa(["animatePages"],400);var d=m();c*=-Math.cos((!b?Math.max(0,(a.Ua||0)+200-d)/200:1)*Math.PI)/2+0.5;if(Math.abs(c)<5){a.B=c=0;pa()}else na(a.Gb,[],"animatePages",a)}a.h.forEach(function(e,f){e&&e.a&&qb(e.a,this.U[f]+c)},a)};function ke(a){E("container",a);this.C=G(a,"data-requires")?a.getAttribute("data-requires").split(" "):i;this.j=a.parentNode.innerHTML;this.size=new L(a);delete this.size.c;delete this.size.b;this.o=k;this.r=this.a=i}ke.prototype.M=function(){if(!this.o){this.o=g;this.a=eb(this.j);this.r=E("container",this.a)[0]}return this.a};ke.prototype.A=function(){if(this.o){this.o=k;this.a=i}};ke.prototype.Ia=function(a){return jb(this.size,a)};
ke.prototype.ca=function(){if(!this.C)return g;return Ya(this.C,g)};var X,le,Zd;function me(){X={orientation:0,size:{c:0,b:0}};bb(W);X.ha=ne();X.Ib=oe();le=pe();Zd=qe();if(!le.length)return k;re();ma(re,100,Infinity,[],"checkState");if(Ca&&!se){N(window,"orientationchange",te);la(function(){window.scrollTo(0,1)},100)}return g}function ne(){if(se)return W;else{var a=document.createElement("div");a.setAttribute("id","chromeContainer");W.appendChild(a);return a}}
function oe(){var a=ab("name","viewport","meta")[0];if(!a){a=document.createElement("meta");a.setAttribute("name","viewport");$a("head")[0].appendChild(a)}return a}function pe(){var a=[];Kc("chrome").forEach(function(b){var c;c=b.getAttribute("data-requires");if(!(c&&!Ya(c.split(" ")))){X.ha.appendChild(b);c=new Kd(b);a.push(c);X.ha.removeChild(b)}});return a}
function qe(){var a=[];Kc("lightbox").forEach(function(b){var c;c=b.getAttribute("data-requires");if(!(c&&!Ya(c.split(" ")))){X.ha.appendChild(b);c=new ke(b);a.push(c);X.ha.removeChild(b)}});return a}function te(){if(X.orientation!==window.orientation){Va();X.orientation=window.orientation;X.orientation%180?X.Ib.setAttribute("content","width=device-height, height=device-width"):X.Ib.setAttribute("content","width=device-width, height=device-height");window.scrollTo(0,1)}}
function Yd(){if(se)return{c:J(W),b:I(W)};else{if(window.pageYOffset||window.pageXOffset)window.scrollTo(0,1);return"innerWidth"in window?{c:window.innerWidth,b:window.innerHeight}:{c:document.documentElement.clientWidth,b:document.documentElement.clientHeight}}}
function re(){var a=Yd(),b;if(a.b!==X.size.b||a.c!==X.size.c){X.size=a;if(!X.R||!X.R.ca()||!X.R.Ia(a)){b=le;var c,d,e,f=i;c=0;for(d=b.length;c<d;c+=1){e=b[c];if(e.ca()&&e.Ia(a)){f=e;break}}b=f;if(!b)return;bb(X.ha);X.R&&X.R.A();X.ha.appendChild(b.M());X.R=b}ae(X.R,a)}};function ld(){Q(window,"unload",ld);rd();Ca&&!se&&Q(window,"orientationchange",te);X.R&&X.R.A();Zd=le=X=i;ue()};var Y={};Y.ja={Sa:"treesaver.ready"};Y.hc=function(){return Y.$a};Y.loaded=function(){return Y.Xb};Y.$a=k;Y.Xb=k;Y.Pa=function(){if(!Y.$a)if(document.body){Y.$a=g;Q(document,"DOMContentLoaded",Y);Q(document,"readystatechange",Y);Q(window,"load",Y);delete Y.ab;M(document,Y.ja.Sa)}else na(Y.Pa)};Y.ob=function(){if("readyState"in document)/complete|loaded/.test(document.readyState)&&Y.Pa();else{var a=document.getElementsByTagName("*").length;if(Y.ab)a===Y.ab&&Y.Pa();else{Y.ab=a;la(Y.ob,100)}}};
Y.handleEvent=function(a){/load|DOMContentLoaded/.test(a.type)?Y.Pa():Y.ob()};N(document,"DOMContentLoaded",Y);N(document,"readystatechange",Y);N(window,"load",Y);Y.ob();var ve={"treesaver-init":{target:"treesaver-init-0.9.1.js",src:"init.js"},"treesaver-core":{target:"treesaver-core-0.9.1.js",src:"core.js"}};ve.ta=function(a){return ve[a].target};ve.ta("treesaver-init");var W,se,we,xe,ye,ze;function ue(){if(se)W.innerHTML=ye;else if(we)W.innerHTML=we;Ae();ja();Gc=i;Ec=0;Fc=[];B.oc();document.documentElement.className="js no-treesaver";document.documentElement.style.display="block"}function Ae(){qa("unboot");Q(document,Y.ja.Sa,Be);delete xe;delete ze}
function Be(){ze=g;if(W=document.getElementById("ts_container")){se=g;ye=W.innerHTML}else{se=k;W=document.body}we=document.body.innerHTML;bb(W);W.innerHTML='<div id="loading">Loading '+document.title+"...</div>";document.documentElement.style.display="block";Ce()}function Ce(){if(xe)if(ze)if(document.body){Ae();N(window,"unload",ld);me()&&hd(we)||ld()}};var De,Ee="pushState"in window.history;function Fe(){var a=document.location.href.indexOf("#");return a===-1?"":document.location.href.substr(a+1)}if(document.location.hash){var Ge=Fe();Ge.charAt(0)==="-"&&Ge.length>=2&&document.location.replace(Ge.substr(1))}function Fd(a,b,c){window.history.pushState(a,b,c)}function Ed(a,b,c){window.history.replaceState(a,b,c)}
if(!Ee){Fd=function(a,b,c){He(a,b,c,k)};Ed=function(a,b,c){He(a,b,c,g)};var Ie=function(a){document.location.hash="#"+a},Je=function(a){document.location.replace("#"+a)},He=function(a,b,c,d){var e="-"+window.escape(c);Nc("history:"+e,{state:a,title:b});if(c===document.location.pathname)e="";De=e;d?Je(e):Ie(e)},Ke=function(){var a=Fe();if(a!==De){a=(De=a)?Oc("history:"+a):{};"onpopstate"in window&&typeof window.onpopstate==="function"&&window.onpopstate.apply(window,[{state:a?a.state:i}])}},Le=function(){return Fe()!==
De};if("onhashchange"in window&&!ua)window.onhashchange=Ke;else{ma(function(){Le()&&Ke()},100,Infinity);if(ya==="msie"){var Me=document.createElement("iframe");document.documentElement.appendChild(Me);Le=function(){var a=Me.contentWindow.document.body.innerHTML;if(a!==De){document.location.hash="#"+(a||"");return g}};Je=function(a){var b=Me.contentWindow.document;if(a!==b.body.innerHTML)b.body.innerHTML=a;document.location.replace("#"+a)};Ie=function(a){var b=Me.contentWindow.document;b.open();b.write("<html><body>"+
a+"</body></html>");b.close();document.location.hash="#"+a}}}};eval("/*@cc_on (function(a,b,c){while(b--)a.createElement(c[b])})(document,21,['abbr','article','aside','audio','canvas','details','figcaption','figure','footer','header','hgroup','mark','menu','meter','nav','output','progress','section','summary','time','video'])@*/");/*
 Copyright 2011 Filipe Fortes ( www.fortes.com ).
 Version: 0.1.

 Licensed under MIT and GPLv2.
*/
if(ta){document.documentElement.style.display="none";B.load();Va();var Ne=function(){xe=g;Ce()},Oe;a:{var Pe=document.getElementsByTagName("link"),Qe,Re=Pe.length;for(Qe=0;Qe<Re;Qe+=1)if(Pe[Qe].rel.toLowerCase().indexOf("resources")!==-1){Oe=Pe[Qe].getAttribute("href");break a}Oe=i}if(Oe)if(Ec)Ec===Jc?Ne():Fc.push(Ne);else{Ec=1;Fc=[Ne];B.ta(Oe,Hc)}else Ne();Y.hc()?Be():N(document,Y.ja.Sa,Be);la(ue,5E3,[],"unboot")}ca("treesaver.VERSION","0.9.1-0-g2041318",void 0); }());
